name: Caller Workflow

on:
  workflow_dispatch:

jobs:
  call-test-secrets:
    uses: ramajeev/StandardChangeCallActions/.github/workflows/TestSecretsbyWFCall.yml@main
    secrets:
      SN_USER_NAME1: ${{ secrets.SN_USER_NAME1 }}
      SN_PWD1: ${{ secrets.SN_PWD1 }}
