# .github/workflows/StandardChange.yml
name: Call ServiceNow API (StandardChange)

on:
  workflow_call:
    inputs:
      start_date:
        description: 'Start date (e.g., 2025-08-29 09:00:00)'
        required: false
        type: string
      end_date:
        description: 'End date (e.g., 2025-09-14 18:00:00)'
        required: false
        type: string
      description:
        description: 'Change description'
        required: false
        type: string
      change_request_hash:
        description: 'ServiceNow change request hash value'
        required: true
        type: string
    secrets:
      SN_USER_NAME1:
        required: true
      SN_PWD1:
        required: true

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Set default values if inputs are empty
        run: |
          FINAL_START_DATE="${{ inputs.start_date }}"
          FINAL_END_DATE="${{ inputs.end_date }}"
          FINAL_DESCRIPTION="${{ inputs.description }}"
          FINAL_CHANGE_HASH="${{ inputs.change_request_hash }}"

          if [ -z "$FINAL_START_DATE" ]; then
            FINAL_START_DATE=$(date '+%Y-%m-%d %H:%M:%S')
          fi

          if [ -z "$FINAL_END_DATE" ]; then
            FINAL_END_DATE=$(date -d "$FINAL_START_DATE + 1 day" '+%Y-%m-%d %H:%M:%S')
          fi

          if [ -z "$FINAL_DESCRIPTION" ]; then
            FINAL_DESCRIPTION="test_description"
          fi
          
          echo "FINAL_START_DATE=$FINAL_START_DATE" >> $GITHUB_ENV
          echo "FINAL_END_DATE=$FINAL_END_DATE" >> $GITHUB_ENV
          echo "FINAL_DESCRIPTION=$FINAL_DESCRIPTION" >> $GITHUB_ENV
          echo "FINAL_CHANGE_HASH=$FINAL_CHANGE_HASH" >> $GITHUB_ENV

      - name: Call ServiceNow API
        run: |
          echo "Calling ServiceNow API with:"
          echo "Start Date: $FINAL_START_DATE"
          echo "End Date: $FINAL_END_DATE"
          echo "Description: $FINAL_DESCRIPTION"
          echo "Change Request Hash: $FINAL_CHANGE_HASH"
          
          if [ -z "$FINAL_START_DATE" ] || [ -z "$FINAL_END_DATE" ] || [ -z "$FINAL_DESCRIPTION" ] || [ -z "$FINAL_CHANGE_HASH" ]; then
            echo "Error: Required environment variables are not set."
            exit 1
          fi

          RESPONSE=$(curl --silent --show-error --fail --request POST "https://dev312158.service-now.com/api/sn_chg_rest/v1/change/standard/$FINAL_CHANGE_HASH" \
            --header "Accept: application/json" \
            --header "Content-Type: application/json" \
            --data "{\"start_date\":\"$FINAL_START_DATE\", \"end_date\":\"$FINAL_END_DATE\", \"short_description\":\"$FINAL_DESCRIPTION\"}" \
            --user "${{ secrets.SN_USER_NAME1 }}:${{ secrets.SN_PWD1 }}")
            
          echo "API Response:"
          echo "$RESPONSE"
