name: Test Secrets

on: workflow_dispatch

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    env:
      SN_USER_NAME: ${{ secrets.SN_USER_NAME1 }}
      SN_PWD: ${{ secrets.SN_PWD1 }}
    steps:
      - name: Print secret lengths
        run: |
          echo "Username length: ${#SN_USER_NAME}"
          echo "Password length: ${#SN_PWD}"
