name: Test Secrets (Reusable)

# This trigger makes the workflow callable by other workflows
on:
  workflow_call:
    inputs:
      start_date:
        description: 'Start date (e.g., 2025-08-29 09:00:00)'
        required: false
        type: string
      end_date:
        description: 'End date (e.g., 2025-09-14 18:00:00)'
        required: false
        type: string
      description:
        description: 'Change description'
        required: false
        type: string
      change_request_hash:
        description: 'ServiceNow change request hash value'
        required: true
        type: string

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    env:
      SN_USER_NAME: ${{ secrets.SN_USER_NAME1 }}
      SN_PWD: ${{ secrets.SN_PWD1 }}
    steps:
      - name: Print secret lengths
        run: |
          echo "Username length: ${#SN_USER_NAME}"
          echo "Password length: ${#SN_PWD}"
