name: Test Secrets (Reusable)

# This trigger makes the workflow callable by other workflows
on:
  workflow_call:
    secrets:
      SN_USER_NAME1:
        required: true
      SN_PWD1:
        required: true
    inputs:
      start_date:
        description: 'Start date (e.g., 2025-08-29 09:00:00)'
        required: false
        type: string
      end_date:
        description: 'End date (e.g., 2025-09-14 18:00:00)'
        required: false
        type: string
      description:
        description: 'Change description'
        required: false
        type: string
      change_request_hash:
        description: 'ServiceNow change request hash value'
        required: true
        type: string

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    env:
      SN_USER_NAME: ${{ secrets.SN_USER_NAME1 }}
      SN_PWD: ${{ secrets.SN_PWD1 }}
      FINAL_START_DATE: ${{ inputs.start_date }}
      FINAL_END_DATE: ${{ inputs.end_date }}
      FINAL_DESCRIPTION: ${{ inputs.description }}
      FINAL_CHANGE_HASH: ${{ inputs.change_request_hash }}

    steps:
      - name: Print secret lengths
        run: |
          echo "Username length: ${#SN_USER_NAME}"
          echo "Password length: ${#SN_PWD}"
          echo "Calling ServiceNow API with:"
          echo "Start Date: $FINAL_START_DATE"
          echo "End Date: $FINAL_END_DATE"
          echo "Description: $FINAL_DESCRIPTION"
          echo "Change Request Hash: $FINAL_CHANGE_HASH"
          
          if [ -z "$FINAL_START_DATE" ] || [ -z "$FINAL_END_DATE" ] || [ -z "$FINAL_DESCRIPTION" ] || [ -z "$FINAL_CHANGE_HASH" ]; then
            echo "Error: Required environment variables are not set."
            exit 1
          fi

          RESPONSE=$(curl --silent --show-error --fail --request POST "https://dev312158.service-now.com/api/sn_chg_rest/v1/change/standard/$FINAL_CHANGE_HASH" \
            --header "Accept: application/json" \
            --header "Content-Type: application/json" \
            --data "{\"start_date\":\"$FINAL_START_DATE\", \"end_date\":\"$FINAL_END_DATE\", \"short_description\":\"$FINAL_DESCRIPTION\"}" \
            --user "${{ secrets.SN_USER_NAME1 }}:${{ secrets.SN_PWD1 }}")
            
          echo "API Response:"
          echo "$RESPONSE"
